// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeRecorder.Models.Services.LocalStorage;

namespace TimeRecorder.Migrations
{
    [DbContext(typeof(TimeRecorderContext))]
    [Migration("20190313152345_mig2")]
    partial class mig2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("TimeRecorder.Models.DTOs.ProjectDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<uint>("Argb");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ProjectDTOs");
                });

            modelBuilder.Entity("TimeRecorder.Models.DTOs.RecordingDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("End");

                    b.Property<int?>("ProjectId");

                    b.Property<DateTime>("Start");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("RecordingDTOs");
                });

            modelBuilder.Entity("TimeRecorder.Models.DTOs.TagDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("RecordingDTOId");

                    b.Property<string>("TagValue");

                    b.HasKey("Id");

                    b.HasIndex("RecordingDTOId");

                    b.HasIndex("TagValue")
                        .IsUnique();

                    b.ToTable("TagDTOs");
                });

            modelBuilder.Entity("TimeRecorder.Models.DTOs.RecordingDTO", b =>
                {
                    b.HasOne("TimeRecorder.Models.DTOs.ProjectDTO", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("TimeRecorder.Models.DTOs.TagDTO", b =>
                {
                    b.HasOne("TimeRecorder.Models.DTOs.RecordingDTO")
                        .WithMany("Tags")
                        .HasForeignKey("RecordingDTOId");
                });
#pragma warning restore 612, 618
        }
    }
}
